import Head from 'next/head';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div>
					<h1 className="text-2xl text-red-200">aaa</h1>
				</div>
				<div className="flex items-center space-x-2">
					<Switch id="airplane-mode" />
					<Label htmlFor="airplane-mode">Airplane Mode</Label>
				</div>
				<Label htmlFor="terms" className="text-blue-600">
					Accept terms and conditions
				</Label>
			</main>
		</>
	);
}
